plugins {
    id "fabric-loom" version "0.11-SNAPSHOT"
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

loom {
    runs {
        client {
            programArgs "--username", "${username}", "--uuid", "${uuid}"
            vmArg "-Dmixin.debug.export=true"
            vmArg "-Dmixin.hotSwap=true"
        }
    }
}

repositories {
    maven {
        name "ParchmentMC"
        url "https://maven.parchmentmc.org"
    }
}

configurations {
    drive
    implementation.extendsFrom drive
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchmentmc_version}@zip")
    }

    drive (group: "com.google.api-client", name: "google-api-client", version: project.api_client_version) {
        exclude(group: "org.apache.httpcomponents")
        exclude(group: "commons-logging")
        exclude(group: "commons-codec")
        exclude(group: "com.google.guava")
        exclude(group: "com.google.code.gson")
        exclude(group: "com.google.code.findbugs")
        exclude(group: "com.google.errorprone")
        exclude(group: "com.google.j2objc")
        exclude(group: "org.checkerframework")
    }
    drive (group: "com.google.oauth-client", name: "google-oauth-client-jetty", version: project.oauth_client_version) {
        exclude(group: "org.apache.httpcomponents")
        exclude(group: "commons-logging")
        exclude(group: "commons-codec")
        exclude(group: "com.google.guava")
        exclude(group: "com.google.code.gson")
        exclude(group: "com.google.code.findbugs")
        exclude(group: "com.google.errorprone")
        exclude(group: "com.google.j2objc")
        exclude(group: "org.checkerframework")
    }
    drive (group: "com.google.apis", name: "google-api-services-drive", version: project.drive_api_version) {
        exclude(group: "org.apache.httpcomponents")
        exclude(group: "commons-logging")
        exclude(group: "commons-codec")
        exclude(group: "com.google.guava")
        exclude(group: "com.google.code.gson")
        exclude(group: "com.google.code.findbugs")
        exclude(group: "com.google.errorprone")
        exclude(group: "com.google.j2objc")
        exclude(group: "org.checkerframework")
    }

    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

String fileName = "${archives_base_name}-mc${minecraft_version}"

jar {
    from configurations.drive.collect {
        it.isDirectory() ? it : zipTree(it)
    }
    excludes = ["drive.v3.json", "META-INF/proguard/**", "META-INF/maven/**"]
    duplicatesStrategy DuplicatesStrategy.INCLUDE
}

remapJar {
    archiveVersion = "v${project.version}"
    archiveBaseName = fileName
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}