org.gradle.jvmargs=-Xmx4G

minecraft_version=1.18.2
fabric_version=0.55.1+1.18.2
loader_version=0.14.6
parchmentmc_version=1.18.2:2022.06.05

# google libs
api_client_version=1.33.2
oauth_client_version=1.33.1
drive_api_version=v3-rev20220214-1.32.1

mod_version=1.2
maven_group=com.stevekung
archives_base_name=ismpbackup