# main
minecraft_version=1.19.4
parchmentmc_version=1.19.3:2023.03.12

# mod
archives_base_name=ismpbackup
maven_group=com.stevekung
mod_version=2.0

# deps
fabric_version=0.82.0+1.19.4
loader_version=0.14.21

# google libs
api_client_version=2.2.0
oauth_client_version=1.34.1
drive_api_version=v3-rev20230423-2.0.0